"use client";

import { useEffect } from "react";
import type { LessonReport } from "@/lib/types";

interface PrintReportProps {
  studentName: string;
  dateLabel: string;
  timeLabel: string;
  durationMin: number | null;
  report: LessonReport;
}

const SECTIONS: { key: keyof LessonReport; label: string }[] = [
  { key: "covered", label: "1. Covered Today" },
  { key: "teacher_notes", label: "2. Teacher's Notes" },
  { key: "assignments", label: "3. Assignments" },
  { key: "next_lesson_plan", label: "4. Next Lesson Plan" },
  { key: "materials", label: "5. Materials / Links" },
];

export default function PrintReport({
  studentName,
  dateLabel,
  timeLabel,
  durationMin,
  report,
}: PrintReportProps) {
  useEffect(() => {
    // Auto-open the print dialog after mount; user can save as PDF.
    const t = setTimeout(() => window.print(), 300);
    return () => clearTimeout(t);
  }, []);

  return (
    <div className="min-h-screen bg-white text-gray-900 p-8 max-w-2xl mx-auto print:p-0">
      <div className="print:hidden mb-6 flex gap-3 items-center">
        <button
          type="button"
          onClick={() => window.print()}
          className="px-4 py-2 bg-amber-600 text-white rounded-md text-sm font-medium"
        >
          Print / Save as PDF
        </button>
        <button
          type="button"
          onClick={() => window.close()}
          className="text-sm text-gray-500 hover:text-gray-900"
        >
          Close
        </button>
      </div>

      <header className="border-b border-gray-300 pb-4 mb-6">
        <h1 className="text-2xl font-bold">Lesson Report</h1>
        <div className="mt-2 text-sm text-gray-700 space-y-0.5">
          <div>
            <span className="font-semibold">Student:</span> {studentName}
          </div>
          <div>
            <span className="font-semibold">Date:</span> {dateLabel} · {timeLabel}
            {durationMin ? ` · ${durationMin} min` : ""}
          </div>
        </div>
      </header>

      <div className="space-y-6">
        {SECTIONS.map(({ key, label }) => {
          const items = report[key];
          return (
            <section key={key}>
              <h2 className="text-base font-semibold uppercase tracking-wide text-gray-800 mb-2">
                {label}
              </h2>
              {items.length === 0 ? (
                <p className="text-sm text-gray-400 italic">—</p>
              ) : (
                <ul className="list-disc pl-5 space-y-1 text-sm text-gray-800 leading-relaxed">
                  {items.map((a, i) => (
                    <li key={i}>{a}</li>
                  ))}
                </ul>
              )}
            </section>
          );
        })}
      </div>

      <footer className="mt-10 pt-4 border-t border-gray-200 text-[11px] text-gray-400 text-center">
        Generated by Keepsy
      </footer>

      <style jsx global>{`
        @media print {
          @page {
            margin: 0.75in;
          }
          body {
            background: white !important;
          }
          .print\\:hidden {
            display: none !important;
          }
        }
      `}</style>
    </div>
  );
}
